#!/usr/bin/env bash
# Diagnose and replace sshd_config with a clean minimal config.
# Backs up the existing config first.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: run as root: sudo bash $0"
    exit 1
fi

SSHD_CFG="/etc/ssh/sshd_config"
BACKUP="${SSHD_CFG}.full-backup.$(date +%Y%m%d%H%M%S)"

echo "=== Current effective sshd config (auth-related) ==="
sshd -T | grep -iE "passwordauth|kbdinteractive|challengeresponse|usepam|authmethod|pubkeyauth|match"
echo ""

echo "=== Raw lines causing the problem ==="
grep -niE "kbdinteractive|challengeresponse|passwordauth|match" "$SSHD_CFG" || true
echo ""

echo "=== Backing up $SSHD_CFG to $BACKUP ==="
cp "$SSHD_CFG" "$BACKUP"
echo "  Done."

echo ""
echo "=== Writing clean minimal sshd_config ==="

# Preserve any non-standard port, HostKey paths, AllowUsers/DenyUsers,
# ListenAddress, and Subsystem lines from the current config.
PORT=$(sshd -T | awk '/^port /{print $2}')
SUBSYSTEM=$(grep -iE "^[[:space:]]*Subsystem" "$BACKUP" | head -1 || echo "Subsystem sftp /usr/libexec/openssh/sftp-server")
HOSTKEYS=$(grep -iE "^[[:space:]]*HostKey" "$BACKUP" || echo "HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key")
ALLOWUSERS=$(grep -iE "^[[:space:]]*(AllowUsers|DenyUsers|AllowGroups|DenyGroups)" "$BACKUP" || true)

cat > "$SSHD_CFG" <<EOF
# Regenerated by fix_ssh2.sh on $(date)
# Original backed up to $BACKUP

Port ${PORT:-22}

${HOSTKEYS}

AuthorizedKeysFile      .ssh/authorized_keys

PasswordAuthentication yes
KbdInteractiveAuthentication yes
ChallengeResponseAuthentication no
UsePAM yes
PubkeyAuthentication yes

PermitRootLogin no
X11Forwarding no
PrintMotd no
AcceptEnv LANG LC_*

${SUBSYSTEM}
${ALLOWUSERS}
EOF

echo "  Written."

echo ""
echo "=== Testing new config ==="
if sshd -t; then
    echo "  Config test passed."
else
    echo "  ERROR: Config test failed — restoring backup."
    cp "$BACKUP" "$SSHD_CFG"
    exit 1
fi

echo ""
echo "=== Restarting sshd ==="
systemctl restart sshd
echo "  Restarted."

echo ""
echo "=== Verification ==="
sshd -T | grep -iE "passwordauth|kbdinteractive|usepam"

echo ""
echo "=== Done. Test SSH now. If it fails, the original is at $BACKUP ==="
