#!/usr/bin/env bash
# =============================================================================
# MFA Module — Time-Based One-Time Password (TOTP) via Google Authenticator PAM
# =============================================================================
# Enforces multi-factor authentication for SSH logins, sudo privilege
# escalation, and GUI (GDM) desktop logins on Rocky Linux 9.
#
# Users authenticate with their password first, then a 6-digit verification
# code generated by any TOTP-compatible app, including:
#   - Microsoft Authenticator  (iOS / Android)
#   - Google Authenticator     (iOS / Android)
#   - Authy                    (iOS / Android / Desktop)
#
# Rocky Linux SELinux note:
#   The DISALLOW_REUSE and RATE_LIMIT token file options require
#   pam_google_authenticator to write a tempfile back to the user home
#   directory, which SELinux silently blocks on Rocky Linux 9. Enrollment
#   uses --allow-reuse and --no-rate-limit to keep the token file read-only
#   from sshd's perspective. faillock (active by default) provides equivalent
#   brute-force protection with a deny threshold of 5 attempts.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../lib/common.sh"
source "$SCRIPT_DIR/../../config.conf"

check_root

GA_LINE="auth required pam_google_authenticator.so nullok"
REMINDER_SRC="${SCRIPT_DIR}/mfa_reminder.sh"
REMINDER_DST="/etc/profile.d/mfa_reminder.sh"

# =============================================================================
# Helpers
# =============================================================================

_header() {
    echo ""
    echo "  ┌─────────────────────────────────────────────────────────┐"
    printf  "  │  %-55s│\n" "$1"
    echo "  └─────────────────────────────────────────────────────────┘"
    echo ""
}

# Add pam_google_authenticator to a PAM file after the last auth line so
# the user is prompted for their password first, then the verification code.
# For sudo files the auth include is changed to substack so that pam_unix
# returning "sufficient" on a correct password does not short-circuit the
# parent stack and skip the TOTP check entirely.
configure_pam_file() {
    local pam_file="$1"
    local label="$2"

    if [[ ! -f "$pam_file" ]]; then
        log_warn "$pam_file not found — skipping $label."
        return
    fi

    backup_file "$pam_file"

    # Idempotent: update the existing line in-place rather than adding a duplicate.
    if grep -q "pam_google_authenticator" "$pam_file"; then
        sed -i "s|.*pam_google_authenticator.*|${GA_LINE}|" "$pam_file"
        log_info "Updated pam_google_authenticator in $pam_file."
        return
    fi

    if grep -qE "^auth[[:space:]]+(include|substack)[[:space:]]+postlogin" "$pam_file"; then
        sed -i "/^auth[[:space:]]*\(include\|substack\)[[:space:]]*postlogin/a ${GA_LINE}" "$pam_file"
    elif grep -q "^auth" "$pam_file"; then
        local last
        last=$(grep -n "^auth" "$pam_file" | tail -1 | cut -d: -f1)
        sed -i "${last}a ${GA_LINE}" "$pam_file"
    else
        echo "$GA_LINE" >> "$pam_file"
    fi

    log_info "Added pam_google_authenticator to $pam_file."
    grep "^auth" "$pam_file" | sed 's/^/    /'
    echo ""
}

_enroll_one_user() {
    local target_user

    while true; do
        read -rp "  Username to enroll: " target_user
        id "$target_user" &>/dev/null && break
        echo "  User '$target_user' does not exist."
    done

    local ga_file="/home/${target_user}/.google_authenticator"

    if [[ -f "$ga_file" ]]; then
        echo ""
        echo "  WARNING: $target_user already has a token enrolled."
        echo "  Continuing will generate a new secret and invalidate any existing"
        echo "  authenticator app registration for this account."
        read -rp "  Overwrite existing enrollment? [y/N]: " _ow
        if [[ ! "${_ow,,}" =~ ^y ]]; then
            log_info "Skipping re-enrollment for $target_user."
            return
        fi
    fi

    echo ""
    echo "  ┌─────────────────────────────────────────────────────────┐"
    echo "  │  Enrolling: ${target_user}"
    echo "  ├─────────────────────────────────────────────────────────┤"
    echo "  │  A QR code will be displayed below.                     │"
    echo "  │  Scan it with your authenticator app:                   │"
    echo "  │    • Microsoft Authenticator  (recommended)             │"
    echo "  │    • Google Authenticator                               │"
    echo "  │    • Authy or any TOTP-compatible app                   │"
    echo "  │                                                         │"
    echo "  │  Emergency codes will also be shown — save them in a   │"
    echo "  │  secure location in case you lose your device.          │"
    echo "  └─────────────────────────────────────────────────────────┘"
    echo ""

    # Options are fully specified via flags so the user cannot accidentally
    # choose DISALLOW_REUSE or RATE_LIMIT, which require write-back to the
    # token file and are silently blocked by SELinux on Rocky Linux 9.
    sudo -u "$target_user" google-authenticator \
        --time-based \
        --force \
        --allow-reuse \
        --no-rate-limit \
        --window-size=3 \
        --emergency-codes=5 \
        --qr-mode=UTF8

    if [[ -f "$ga_file" ]]; then
        # google-authenticator creates the file as mode 400 on Rocky Linux.
        # pam_google_authenticator needs 600 to update the file on login.
        # restorecon ensures the auth_home_t SELinux context is set so
        # sshd_t can read the file.
        chmod 600 "$ga_file"
        chown "${target_user}:${target_user}" "$ga_file"
        restorecon "$ga_file" 2>/dev/null || true
        log_info "Token file secured for $target_user."
    fi

    echo ""
    echo "  Enrollment complete for $target_user."
    echo "  Login flow: Password → 6-digit verification code from your app."
}

# =============================================================================
# Menu: Install / Configure MFA
# =============================================================================

menu_install() {
    _header "Install / Configure MFA"

    echo "  This option installs the Google Authenticator PAM module and"
    echo "  configures the selected login methods to require a verification"
    echo "  code in addition to the user's password."
    echo ""
    echo "  Supported authenticator apps:"
    echo "    • Microsoft Authenticator  (iOS / Android)"
    echo "    • Google Authenticator     (iOS / Android)"
    echo "    • Authy or any TOTP-compatible app"
    echo ""

    # -- Package -----------------------------------------------------------------
    log_section "Install Google Authenticator PAM module"

    if ! rpm -q google-authenticator &>/dev/null; then
        if ! rpm -q epel-release &>/dev/null; then
            log_info "Installing EPEL repository..."
            dnf install -y epel-release
        fi
        log_info "Installing google-authenticator..."
        dnf install -y google-authenticator
    else
        log_info "google-authenticator already installed."
    fi

    # -- Enforcement points ------------------------------------------------------
    echo ""
    echo "  Where should MFA be required?"
    echo ""
    echo "    1) SSH only          — remote logins via SSH                (default)"
    echo "    2) sudo only         — privilege escalation via sudo"
    echo "    3) GUI login only    — GDM desktop login screen"
    echo "    4) SSH + sudo"
    echo "    5) SSH + GUI"
    echo "    6) sudo + GUI"
    echo "    7) SSH + sudo + GUI  — all login methods"
    echo ""
    read -rp "  Selection [1-7, default=1]: " _sel
    echo ""

    local DO_SSH=0 DO_SUDO=0 DO_GUI=0
    case "${_sel:-1}" in
        1) DO_SSH=1 ;;
        2) DO_SUDO=1 ;;
        3) DO_GUI=1 ;;
        4) DO_SSH=1; DO_SUDO=1 ;;
        5) DO_SSH=1; DO_GUI=1 ;;
        6) DO_SUDO=1; DO_GUI=1 ;;
        7) DO_SSH=1; DO_SUDO=1; DO_GUI=1 ;;
        *) log_warn "Invalid selection — defaulting to SSH only."; DO_SSH=1 ;;
    esac

    echo "  Will configure:"
    [ "$DO_SSH"  -eq 1 ] && echo "    SSH  — /etc/pam.d/sshd + sshd_config"
    [ "$DO_SUDO" -eq 1 ] && echo "    sudo — /etc/pam.d/sudo + sudo-i"
    [ "$DO_GUI"  -eq 1 ] && echo "    GUI  — /etc/pam.d/gdm-password"
    echo ""
    read -rp "  Proceed? [Y/n]: " _ok
    [[ "${_ok,,}" =~ ^n ]] && { log_info "Cancelled."; return; }

    # -- PAM ---------------------------------------------------------------------
    log_section "Configure PAM"

    if [ "$DO_SSH" -eq 1 ]; then
        configure_pam_file "/etc/pam.d/sshd" "SSH"
    fi

    if [ "$DO_SUDO" -eq 1 ]; then
        for f in /etc/pam.d/sudo /etc/pam.d/sudo-i; do
            [[ -f "$f" ]] || continue
            sed -i 's/^auth[[:space:]]*include[[:space:]]*system-auth/auth       substack     system-auth/' "$f"
            sed -i 's/^auth[[:space:]]*include[[:space:]]*sudo$/auth       substack     sudo/' "$f"
        done
        configure_pam_file "/etc/pam.d/sudo"   "sudo"
        configure_pam_file "/etc/pam.d/sudo-i" "sudo-i"
    fi

    if [ "$DO_GUI" -eq 1 ]; then
        configure_pam_file "/etc/pam.d/gdm-password" "GDM"
    fi

    # -- sshd_config -------------------------------------------------------------
    if [ "$DO_SSH" -eq 1 ]; then
        log_section "Configure sshd_config"

        local SSHD_CFG="/etc/ssh/sshd_config"
        local ver_str openssh_major KBD_DIRECTIVE
        ver_str=$(sshd -V 2>&1 || true)
        openssh_major=$(echo "$ver_str" | grep -oP 'OpenSSH_\K[0-9]+' || echo "8")
        openssh_major="${openssh_major:-8}"
        if [ "$openssh_major" -ge 8 ]; then
            KBD_DIRECTIVE="KbdInteractiveAuthentication"
        else
            KBD_DIRECTIVE="ChallengeResponseAuthentication"
        fi
        log_info "OpenSSH ${openssh_major} — using ${KBD_DIRECTIVE}"

        backup_file "$SSHD_CFG"

        if grep -qiE "^[[:space:]]*UsePAM" "$SSHD_CFG"; then
            sed -i -E 's|^[[:space:]]*UsePAM.*|UsePAM yes|I' "$SSHD_CFG"
        else
            echo "UsePAM yes" >> "$SSHD_CFG"
        fi

        sed -i -E '/^[[:space:]]*(KbdInteractiveAuthentication|ChallengeResponseAuthentication)/d' "$SSHD_CFG"
        echo "${KBD_DIRECTIVE} yes" >> "$SSHD_CFG"
        sed -i -E '/^[[:space:]]*AuthenticationMethods/d' "$SSHD_CFG"

        if ! sshd -t; then
            log_error "sshd_config validation failed — restoring backup."
            local bak
            bak=$(ls -t "${SSHD_CFG}".bak.* 2>/dev/null | head -1 || true)
            [[ -n "$bak" ]] && cp "$bak" "$SSHD_CFG"
            return
        fi

        systemctl restart sshd && log_info "sshd restarted." || log_error "sshd restart failed."
    fi

    # -- SELinux -----------------------------------------------------------------
    if command -v getenforce &>/dev/null && [[ "$(getenforce 2>/dev/null)" == "Enforcing" ]]; then
        log_section "SELinux"
        log_info "Enabling authlogin_yubikey boolean to allow PAM module file access..."
        setsebool -P authlogin_yubikey on \
            && log_info "authlogin_yubikey enabled." \
            || log_warn "Could not set authlogin_yubikey — run manually: setsebool -P authlogin_yubikey on"
    fi

    log_section "MFA configuration complete"
    [ "$DO_SSH"  -eq 1 ] && log_info "SSH:  Password → Verification code"
    [ "$DO_SUDO" -eq 1 ] && log_info "sudo: Password → Verification code"
    [ "$DO_GUI"  -eq 1 ] && log_info "GUI:  Password → Verification code"
    echo ""
    echo "  Users without a token enrolled can still log in (nullok is active)."
    echo "  Use 'Enroll a user' from the main menu to register each account."
    echo ""
    read -rp "  Enroll a user now? [y/N]: " _enroll
    [[ "${_enroll,,}" =~ ^y ]] && menu_enroll
}

# =============================================================================
# Menu: Enroll a user
# =============================================================================

menu_enroll() {
    _header "Enroll a User"

    echo "  Generates a TOTP secret for a user account and displays a QR code."
    echo "  The user must scan the QR code with their authenticator app before"
    echo "  MFA will be required for their logins."
    echo ""

    _enroll_one_user

    while true; do
        echo ""
        read -rp "  Enroll another user? [y/N]: " _more
        [[ "${_more,,}" =~ ^y ]] || break
        _enroll_one_user
    done
}

# =============================================================================
# Menu: Tools
# =============================================================================

tool_enforce_mfa() {
    _header "Enforce MFA — Remove nullok"

    echo "  Currently, users without a TOTP token can log in with their password"
    echo "  alone (nullok). Removing nullok makes MFA strictly required — any"
    echo "  account without an enrolled token will be denied access entirely."
    echo ""
    echo "  Only do this once every user account has been enrolled."
    echo ""

    # Check for unenrolled users before proceeding.
    local unenrolled_names=()
    while IFS=: read -r uname _ uid _ _ homedir _; do
        [ "$uid" -lt 1000 ] && continue
        [ "$uname" = "nobody" ] && continue
        [[ -f "${homedir}/.google_authenticator" ]] || unenrolled_names+=("$uname")
    done < /etc/passwd

    if [ "${#unenrolled_names[@]}" -gt 0 ]; then
        echo "  WARNING: The following users are NOT enrolled and will be locked out:"
        for u in "${unenrolled_names[@]}"; do
            echo "    • $u"
        done
        echo ""
        read -rp "  Continue anyway? [y/N]: " _force
        [[ "${_force,,}" =~ ^y ]] || { log_info "Cancelled."; return; }
        echo ""
    fi

    # Find every PAM file that has pam_google_authenticator configured.
    local pam_files=()
    while IFS= read -r f; do
        pam_files+=("$f")
    done < <(grep -rl "pam_google_authenticator" /etc/pam.d/ 2>/dev/null)

    if [ "${#pam_files[@]}" -eq 0 ]; then
        log_warn "No PAM files with pam_google_authenticator found — has MFA been installed?"
        return
    fi

    echo "  PAM files that will be updated:"
    for f in "${pam_files[@]}"; do
        if grep -q "nullok" "$f"; then
            echo "    $f"
        fi
    done
    echo ""
    read -rp "  Remove nullok and enforce MFA for all users? [y/N]: " _confirm
    [[ "${_confirm,,}" =~ ^y ]] || { log_info "Cancelled."; return; }
    echo ""

    local changed=0
    for f in "${pam_files[@]}"; do
        if grep -q "pam_google_authenticator.*nullok" "$f"; then
            backup_file "$f"
            sed -i 's/\(pam_google_authenticator\.so\)[[:space:]]*nullok/\1/' "$f"
            log_info "Removed nullok from $f"
            changed=$(( changed + 1 ))
        fi
    done

    if [ "$changed" -eq 0 ]; then
        log_info "nullok was not present in any PAM file — MFA is already enforced."
    else
        echo ""
        log_info "MFA is now strictly enforced. Users without a token will be denied access."
        log_info "To re-enable nullok (allow unenrolled users), use 'Relax MFA enforcement'."
    fi
    echo ""
}

tool_relax_mfa() {
    _header "Relax MFA Enforcement — Restore nullok"

    echo "  Adds nullok back to pam_google_authenticator in all configured PAM"
    echo "  files, allowing users without a TOTP token to log in with their"
    echo "  password alone. Use this to safely onboard new users or recover"
    echo "  from a lockout situation."
    echo ""

    local pam_files=()
    while IFS= read -r f; do
        pam_files+=("$f")
    done < <(grep -rl "pam_google_authenticator" /etc/pam.d/ 2>/dev/null)

    if [ "${#pam_files[@]}" -eq 0 ]; then
        log_warn "No PAM files with pam_google_authenticator found — has MFA been installed?"
        return
    fi

    echo "  PAM files that will be updated:"
    for f in "${pam_files[@]}"; do
        if ! grep -q "nullok" "$f"; then
            echo "    $f"
        fi
    done
    echo ""
    read -rp "  Restore nullok? [y/N]: " _confirm
    [[ "${_confirm,,}" =~ ^y ]] || { log_info "Cancelled."; return; }
    echo ""

    local changed=0
    for f in "${pam_files[@]}"; do
        if grep -q "pam_google_authenticator" "$f" && ! grep -q "nullok" "$f"; then
            backup_file "$f"
            sed -i 's/\(pam_google_authenticator\.so\)/\1 nullok/' "$f"
            log_info "Restored nullok in $f"
            changed=$(( changed + 1 ))
        fi
    done

    if [ "$changed" -eq 0 ]; then
        log_info "nullok already present in all PAM files — nothing changed."
    else
        echo ""
        log_info "Unenrolled users can now log in with their password alone."
    fi
    echo ""
}

tool_disable_user_mfa() {
    _header "Disable MFA for a User"

    echo "  Removes a user's TOTP token file (~/.google_authenticator)."
    echo "  The user will no longer be prompted for a verification code."
    echo "  Their account will still be protected by password authentication."
    echo ""
    echo "  Use this to reset a lost authenticator or temporarily bypass MFA"
    echo "  for a specific account without affecting the rest of the system."
    echo ""

    local target_user
    while true; do
        read -rp "  Username to disable MFA for: " target_user
        id "$target_user" &>/dev/null && break
        echo "  User '$target_user' does not exist."
    done

    local homedir
    homedir=$(getent passwd "$target_user" | cut -d: -f6)
    local ga_file="${homedir}/.google_authenticator"

    if [[ ! -f "$ga_file" ]]; then
        echo ""
        log_info "$target_user does not have MFA enrolled — nothing to remove."
        return
    fi

    echo ""
    echo "  WARNING: This will remove the TOTP token for '$target_user'."
    echo "  The user will be able to log in with their password alone."
    read -rp "  Confirm? [y/N]: " _confirm
    if [[ ! "${_confirm,,}" =~ ^y ]]; then
        log_info "Cancelled."
        return
    fi

    rm -f "$ga_file"
    log_info "MFA token removed for $target_user."
    log_info "The user can re-enroll at any time using 'Enroll a user' from the main menu."
    echo ""
}

menu_tools() {
    while true; do
        _header "MFA Tools"
        echo "    1) Enrollment status report   — show which users have MFA registered"
        echo "    2) Disable MFA for a user    — remove a user's TOTP token"
        echo "    3) Enforce MFA (remove nullok) — require MFA for all users; locks out unenrolled accounts"
        echo "    4) Relax MFA (restore nullok)  — allow unenrolled users to log in with password only"
        echo "    5) Enable login reminder      — display a notice to unenrolled users at login"
        echo "    6) Disable login reminder     — remove the login notice"
        echo "    7) Back"
        echo ""
        read -rp "  Selection [1-7]: " _t
        echo ""

        case "${_t}" in
            1) tool_enrollment_status ;;
            2) tool_disable_user_mfa ;;
            3) tool_enforce_mfa ;;
            4) tool_relax_mfa ;;
            5) tool_reminder_enable ;;
            6) tool_reminder_disable ;;
            7) return ;;
            *) echo "  Invalid selection." ;;
        esac
    done
}

tool_enrollment_status() {
    _header "MFA Enrollment Status"

    echo "  Lists all standard user accounts (UID 1000+) and whether each has"
    echo "  a TOTP token registered. Users shown as NOT ENROLLED can still log"
    echo "  in while nullok is active, but will not be prompted for a code."
    echo ""

    local enrolled=0 unenrolled=0

    printf "  %-20s %-14s %s\n" "USER" "ENROLLED" "TOKEN REGISTERED"
    printf "  %-20s %-14s %s\n" "────────────────────" "──────────────" "────────────────"

    while IFS=: read -r uname _ uid _ _ homedir _; do
        [ "$uid" -lt 1000 ] && continue
        [ "$uname" = "nobody" ] && continue

        local ga_file="${homedir}/.google_authenticator"
        if [[ -f "$ga_file" ]]; then
            local age
            age=$(date -r "$ga_file" "+%Y-%m-%d %H:%M" 2>/dev/null || echo "unknown")
            printf "  %-20s %-14s %s\n" "$uname" "YES" "$age"
            enrolled=$(( enrolled + 1 ))
        else
            printf "  %-20s %-14s %s\n" "$uname" "NO" "-"
            unenrolled=$(( unenrolled + 1 ))
        fi
    done < /etc/passwd

    echo ""
    printf "  Enrolled: %d   Not enrolled: %d   Total: %d\n" \
        "$enrolled" "$unenrolled" "$(( enrolled + unenrolled ))"
    echo ""
}

tool_reminder_enable() {
    _header "Enable Login Reminder"

    echo "  Installs a script to /etc/profile.d/ that displays an enrollment"
    echo "  notice to any user who logs in without a TOTP token registered."
    echo "  The notice disappears automatically once the user enrolls."
    echo ""

    if [[ ! -f "$REMINDER_SRC" ]]; then
        log_warn "mfa_reminder.sh not found at $REMINDER_SRC"
        return
    fi

    cp "$REMINDER_SRC" "$REMINDER_DST"
    chmod 644 "$REMINDER_DST"
    log_info "Login reminder installed at $REMINDER_DST"
    log_info "Unenrolled users will see the enrollment notice at every login."
}

tool_reminder_disable() {
    _header "Disable Login Reminder"

    echo "  Removes the enrollment reminder from /etc/profile.d/."
    echo "  Users will no longer see the notice when logging in."
    echo ""

    if [[ -f "$REMINDER_DST" ]]; then
        rm -f "$REMINDER_DST"
        log_info "Login reminder removed."
    else
        log_info "Login reminder is not currently installed — nothing to remove."
    fi
}

# =============================================================================
# Main landing page
# =============================================================================

while true; do
    _header "MFA Module — Time-Based One-Time Password (TOTP)"
    echo "  Configures multi-factor authentication using the Google Authenticator"
    echo "  PAM module. Works with Microsoft Authenticator, Google Authenticator,"
    echo "  Authy, and any other TOTP-compatible app."
    echo ""
    echo "    1) Install / Configure MFA   — set up MFA enforcement for SSH, sudo, or GUI"
    echo "    2) Enroll a user             — generate a TOTP token and display QR code"
    echo "    3) Tools                     — enrollment status report and login reminder"
    echo "    4) Exit"
    echo ""
    read -rp "  Selection [1-4, default=1]: " _main
    echo ""

    case "${_main:-1}" in
        1) menu_install ;;
        2) menu_enroll ;;
        3) menu_tools ;;
        4) log_info "Exiting MFA module."; exit 0 ;;
        *) echo "  Invalid selection." ;;
    esac
done
